n3b_shop_basket:
    pattern:  /
    defaults: { _controller: basket:show }

n3b_shop_basket_add:
    pattern:  /add/{productId}
    defaults: { _controller: basket:addProduct }
    requirements:
        productId:  \d+

n3b_shop_basket_decrease:
    pattern:  /decrease/{itemId}
    defaults: { _controller: basket:decreaseBasketItemQuantity }
    requirements:
        productId:  \d+

n3b_shop_basket_increase:
    pattern:  /increase/{itemId}
    defaults: { _controller: basket:increaseBasketItemQuantity }
    requirements:
        productId:  \d+

n3b_shop_basket_remove:
    pattern:  /remove/{itemId}
    defaults: { _controller: basket:removeItem }
    requirements:
        productId:  \d+

n3b_shop_basket_quantity:
    pattern:  /update/{itemId}/{quantity}
    defaults: { _controller: basket:updateQuantity, quantity: 1 }
    requirements:
        itemId:     \d+
        quantity:   \d+

n3b_shop_basket_mini:
    pattern:  /mini
    defaults: { _controller: basket:showMini }
