n3b_shop_catalog_search:
  pattern:            /search
  defaults:           { _controller: catalog:search }

n3b_shop_catalog_products:
  pattern:            /{slugStr}
  defaults:           { _controller: catalog:products }

n3b_shop_catalog_product:
  pattern:            /product/{slug}
  defaults:           { _controller: catalog:product }
